[package]
name = "arre-life-roulette-rust-logger-macro"
version = "0.1.0"
edition = "2021"

[lib]
crate_type = ["proc-macro"]

[dependencies]
syn = { version = "2.0.15", features = ["full"] }
quote = "1.0.26"